### PR TITLE
Add basic paper management

### LINKED ISSUE #2: Port core synchronization protocol
The synchronization protocol implemented in \BlueLaTeX 1.0 must be ported to akka-http.
It does not change the core implementation, only the interface using routes.

Takes part to resolution of bluelatex/bluelatex#4

### PR DESCRIPTION
**Pull request by satabin**
Papers can be:
- created
- deleted
- updated with new directories, new files, synchronized or not

The synchronizer is organized as different actors, one for each paper which contains one for each connected peer.

```
        +--------------+
        | Synchronizer |
        +--------------+
      +---^     ^     ^-------+
      |         |             |
 +--------+ +--------+    +--------+
 | Paper1 | | Paper2 |... | Paperk |
 +--------+ +--------+    +--------+
           +--^  ^--+
           |        |
        +-----+ +-----+
        |Peer1| |Peer2|
        +-----+ +-----+
```

Fixes #2

[Review on Reviewable](https://reviewable.io/reviews/bluelatex/bluelatex-server/8)

### CODE REVIEW

**Comment by ghost** [comment]
Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[core/src/main/scala/bluelatex/persistence/data.scala, line 16 [r1]](https://reviewable.io:443/reviews/bluelatex/bluelatex-server/8#-K7ZWgBqr17B7drZTYnr:-K7ZWgBsLrQ27dEd_lDY:-323732512) ([raw file](https://github.com/bluelatex/bluelatex-server/blob/8214c85fcbcf2153803fc052374cae037cf4b13e/core/src/main/scala/bluelatex/persistence/data.scala#L16)):_
+package persistence?

---

_[core/src/main/scala/bluelatex/persistence/data.scala, line 22 [r1]](https://reviewable.io:443/reviews/bluelatex/bluelatex-server/8#-K7ZQD8W1t7zto9SeiNx:-K7ZQD8ZzBTqKvW9Rh3S:610327414) ([raw file](https://github.com/bluelatex/bluelatex-server/blob/8214c85fcbcf2153803fc052374cae037cf4b13e/core/src/main/scala/bluelatex/persistence/data.scala#L22)):_
Remove?

---

_[core/src/main/scala/bluelatex/synchro/Peer.scala, line 46 [r1]](https://reviewable.io:443/reviews/bluelatex/bluelatex-server/8#-K7ZTs5CSXqkf2PL0kzS:-K7ZTs5F2kfjONYepPaT:662518481) ([raw file](https://github.com/bluelatex/bluelatex-server/blob/8214c85fcbcf2153803fc052374cae037cf4b13e/core/src/main/scala/bluelatex/synchro/Peer.scala#L46)):_
Meaningless

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bluelatex/bluelatex-server/8)_

**Comment by satabin** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[core/src/main/scala/bluelatex/persistence/data.scala, line 16 [r1]](https://reviewable.io:443/reviews/bluelatex/bluelatex-server/8#-K7ZWgBqr17B7drZTYnr:-K7_eOQX51OT_ROI_sG2:-1267965400) ([raw file](https://github.com/bluelatex/bluelatex-server/blob/8214c85fcbcf2153803fc052374cae037cf4b13e/core/src/main/scala/bluelatex/persistence/data.scala#L16)):_
No data is used for synchronization and persistence. It is an intrinsic concept of \BlueLaTeX

---

_[core/src/main/scala/bluelatex/persistence/data.scala, line 22 [r1]](https://reviewable.io:443/reviews/bluelatex/bluelatex-server/8#-K7ZQD8W1t7zto9SeiNx:-K7_ekTs0fFrdtgkOirL:439504638) ([raw file](https://github.com/bluelatex/bluelatex-server/blob/8214c85fcbcf2153803fc052374cae037cf4b13e/core/src/main/scala/bluelatex/persistence/data.scala#L22)):_
Legacy comment to be removed indeed.

---

_[core/src/main/scala/bluelatex/synchro/Peer.scala, line 46 [r1]](https://reviewable.io:443/reviews/bluelatex/bluelatex-server/8#-K7ZTs5CSXqkf2PL0kzS:-K7_ed1EinQsv0IKf9J1:-486402025) ([raw file](https://github.com/bluelatex/bluelatex-server/blob/8214c85fcbcf2153803fc052374cae037cf4b13e/core/src/main/scala/bluelatex/synchro/Peer.scala#L46)):_
Right

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bluelatex/bluelatex-server/8)_

**Comment by satabin** [comment]
Review status: 22 of 25 files reviewed at latest revision, 3 unresolved discussions.

---

_[core/src/main/scala/bluelatex/data.scala, line 22 [r1]](https://reviewable.io:443/reviews/bluelatex/bluelatex-server/8#-K7ZQD8W1t7zto9SeiNx:-K7_gclNzksDJC90atRm:-499146009) ([raw file](https://github.com/bluelatex/bluelatex-server/blob/8214c85fcbcf2153803fc052374cae037cf4b13e/core/src/main/scala/bluelatex/data.scala#L22)):_
Done.

---

_[core/src/main/scala/bluelatex/synchro/Peer.scala, line 46 [r1]](https://reviewable.io:443/reviews/bluelatex/bluelatex-server/8#-K7ZTs5CSXqkf2PL0kzS:-K7_geFYH9n9slOjp2UG:-499146009) ([raw file](https://github.com/bluelatex/bluelatex-server/blob/8214c85fcbcf2153803fc052374cae037cf4b13e/core/src/main/scala/bluelatex/synchro/Peer.scala#L46)):_
Done.

---

_[core/src/main/scala/bluelatex/persistence/data.scala, line 16 [r1]](https://reviewable.io:443/reviews/bluelatex/bluelatex-server/8#-K7ZWgBqr17B7drZTYnr:-K7_fPvtpnvINGBNRmzO:-499146009) ([raw file](https://github.com/bluelatex/bluelatex-server/blob/8214c85fcbcf2153803fc052374cae037cf4b13e/core/src/main/scala/bluelatex/persistence/data.scala#L16)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bluelatex/bluelatex-server/8)_

**Comment by ghost** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bluelatex/bluelatex-server/8)_

**Pull request merged**
